/**
 * 画面項目 ID 自動採番 + 命名プレフィックス導出ロジック (#333 / #1380)。
 *
 * `isAutoGeneratedId` は frontend / backend 共有のため `@harmony/shared` に集約済 (#1380)。
 * `generateAutoId` / `getFieldTypePrefix` は frontend のみで使用する純粋関数 (FieldType
 * 型に依存) のため frontend 配下に保持する。
 *
 * 自動生成 ID パターン:
 *   - 旧自動採番: `field_[0-9a-f]{8}` (field_69f9561e 等)
 *   - 種別+連番:  `<prefix><数字>` (textInput1, select3 等)
 *
 * それ以外 (userName, 郵便番号, etc.) は「命名済み」として上書き禁止。
 */
import type { FieldType } from "../types/v3";

export { isAutoGeneratedId } from "@harmony/shared";

/**
 * 指定プレフィックスの次の連番 ID を返す。
 * existing に `prefix + 数字` の形式が含まれていれば最大値 +1、
 * なければ `prefix1` を返す。
 */
export function generateAutoId(prefix: string, existing: string[]): string {
  const pattern = new RegExp(`^${prefix}(\\d+)$`);
  let maxN = 0;
  for (const id of existing) {
    const m = id.match(pattern);
    if (m) maxN = Math.max(maxN, parseInt(m[1], 10));
  }
  return `${prefix}${maxN + 1}`;
}

/**
 * ScreenItem の型 (FieldType) から命名プレフィックスを返す (#334)。
 * GrapesJS 要素の HTML タイプと 1:1 ではなく、論理的なデータ型から最も近いプレフィックスを選択。
 */
export function getFieldTypePrefix(type: FieldType): string {
  if (typeof type !== "string") return "field";
  switch (type) {
    case "number":
    case "integer": return "numberInput";
    case "boolean": return "checkbox";
    case "date": return "dateInput";
    case "datetime": return "datetimeInput";
    default: return "textInput";
  }
}
