/**
 * screenItemNaming.ts (#333 / #1380 で `@harmony/shared` に集約)
 *
 * 画面項目 ID の「自動生成 / 命名済み」判定ロジック。
 *
 * 自動生成 ID パターン:
 *   - 旧自動採番: `field_[0-9a-f]{8}`  (field_69f9561e 等)
 *   - 種別+連番:  `<prefix><数字>`      (textInput1, select3 等)
 *
 * それ以外 (userName, 郵便番号, etc.) は「命名済み」として上書き禁止。
 *
 * 経緯:
 *   - frontend `src/utils/screenItemNaming.ts` と backend `src/renameContext.ts` に
 *     完全同一ロジックが複製されていた (frontend は AI 命名 UI、backend は MCP
 *     rename 用 context 収集で共通使用)。
 *   - PR #1378 (#1375) で `@harmony/shared` npm workspaces package を新設。
 *   - #1380 で本ロジックを単一定義として `@harmony/shared` 配下へ移動。
 *   - frontend に残存する `generateAutoId` / `getFieldTypePrefix` は `FieldType` 型
 *     (frontend/src/types/v3) 依存のため shared 化対象外、frontend のみで保持する。
 */

const OLD_AUTO_PATTERN = /^field_[0-9a-f]{8}$/;

/** getItemIdPrefix が返しうる全プレフィックスと "field"(連番形式) */
const SEQUENTIAL_PREFIXES = [
  // 入力系
  "textInput", "passwordInput", "numberInput",
  "dateInput", "datetimeInput", "timeInput", "monthInput", "weekInput",
  "emailInput", "telInput", "urlInput", "fileInput",
  "checkbox", "radio", "textarea", "select", "button", "field",
  // 出力系 (#359)
  "textDisplay", "valueLabel", "statusBadge", "tableView",
];

const SEQUENTIAL_PATTERN = new RegExp(
  `^(${SEQUENTIAL_PREFIXES.join("|")})\\d+$`,
);

/**
 * ID が自動生成済み (上書き可) かどうかを返す。
 * - 旧自動採番 (`field_xxxxxxxx`) → true
 * - 種別+連番 (`textInput1` 等) → true
 * - それ以外 → false (命名済み、保護対象)
 */
export function isAutoGeneratedId(id: string): boolean {
  return OLD_AUTO_PATTERN.test(id) || SEQUENTIAL_PATTERN.test(id);
}
